name: "Build & test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js v20
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - run: |
        npm install
        npm run all

